name: TownyRankLimiter
version: '${project.version}'
main: org.dexterx.mc.townyranklimiter.TownyRankLimiter
api-version: '1.20'
commands:
  trank:
    description: Towny rank limiter commands
    usage: /trank reload
    permission: townyranklimiter.reload
    permission-message: "You do not have permission to execute this command."
permissions:
  townyranklimiter.reload:
    description: Allows reloading the TownyRankLimiter configuration.
    default: op
